from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional


@dataclass(frozen=True)
class ActionProposal:
    """
    Immutable proposal generated by Jessica.

    This does NOT execute anything.
    It only describes a possible action.
    """

    proposal_id: str
    description: str
    reasoning: str
    actions: List[str]

    risk_level: str  # low / medium / high
    requires_permission: bool = True

    created_at: datetime = field(default_factory=datetime.utcnow)
    status: str = "pending"  # pending / approved / rejected

    def is_high_risk(self) -> bool:
        return self.risk_level == "high"
