"""
Improvement Generator - Generate concrete code improvements based on analysis.

Creates pull requests with:
- Optimized code implementations
- Performance justifications
- Risk assessments
- Backward compatibility checks
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional
from enum import Enum
from datetime import datetime


class ImprovementType(Enum):
    """Type of code improvement."""
    VECTORIZATION = "vectorization"      # Use numpy/torch
    CACHING = "caching"                  # Add @cache or memoization
    PARALLELIZATION = "parallelization"  # Use multiprocessing
    ALGORITHM = "algorithm"              # Better algorithm
    INDEXING = "indexing"                # Add data structure index
    PRECOMPUTATION = "precompute"        # Pre-compute invariants


@dataclass
class CodeFix:
    """A specific code improvement."""
    improvement_type: ImprovementType
    file_path: str
    line_range: tuple  # (start_line, end_line)
    original_code: str
    improved_code: str
    explanation: str
    risk_level: float  # 0.0-1.0 (0=safe, 1=risky)
    performance_gain: float  # Expected speedup factor
    backwards_compatible: bool
    test_cases: List[str] = field(default_factory=list)


@dataclass
class PullRequest:
    """A self-improvement pull request generated by Jessica."""
    pr_id: str
    title: str
    description: str
    changes: List[CodeFix]
    created_at: datetime
    risk_assessment: str
    expected_outcome: str
    estimated_improvement: float  # Expected speedup factor
    affected_components: List[str]


class ImprovementGenerator:
    """Generate code improvements from analysis results."""
    
    def __init__(self):
        self.templates = self._init_templates()
    
    def _init_templates(self) -> Dict:
        """Initialize improvement code templates."""
        return {
            'caching_decorator': '''
from functools import lru_cache

@lru_cache(maxsize=128)
def {function_name}({args}):
    """Cached version of {original_function}."""
    {original_body}
''',
            
            'vectorization_pattern': '''
import numpy as np

# Original: list comprehension in loop
# Optimized: vectorized numpy operation
{variable_name} = np.array([{operation}])
result = {vectorized_operation}({variable_name})
''',
            
            'parallelization_pattern': '''
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor

with {executor_type}(max_workers={worker_count}) as executor:
    results = list(executor.map({function}, {iterable}))
''',
            
            'precomputation_pattern': '''
# Pre-compute invariants at initialization time
class {class_name}:
    def __init__(self):
        # Pre-compute lookup table
        self.{cache_name} = self._build_lookup_table()
    
    def _build_lookup_table(self):
        return {{key: computed_value for key, computed_value in ...}}
''',
        }
    
    def generate_caching_fix(self, function_name: str, file_path: str, 
                             line_range: tuple, original_code: str) -> CodeFix:
        """Generate a caching improvement for a frequently-called function."""
        
        improved_code = f'''from functools import lru_cache

@lru_cache(maxsize=256)
{original_code}'''
        
        return CodeFix(
            improvement_type=ImprovementType.CACHING,
            file_path=file_path,
            line_range=line_range,
            original_code=original_code,
            improved_code=improved_code,
            explanation=f"Added LRU caching to {function_name} to avoid recomputing identical inputs",
            risk_level=0.1,
            performance_gain=3.0,  # 3x speedup typical for cached function
            backwards_compatible=True,
            test_cases=[
                f"Test that {function_name}(...) returns same result multiple times",
                f"Test that cache size doesn't exceed 256 entries",
            ],
        )
    
    def generate_vectorization_fix(self, file_path: str, line_range: tuple,
                                   original_code: str, operation: str) -> CodeFix:
        """Generate a numpy vectorization improvement."""
        
        improved_code = f'''import numpy as np

# Vectorized operation (replacing loop)
# Original: loop iteration
# Optimized: numpy broadcast
{operation}
'''
        
        return CodeFix(
            improvement_type=ImprovementType.VECTORIZATION,
            file_path=file_path,
            line_range=line_range,
            original_code=original_code,
            improved_code=improved_code,
            explanation="Replaced Python loop with numpy vectorization for O(1) speedup",
            risk_level=0.15,
            performance_gain=10.0,  # 10x+ typical for vectorization
            backwards_compatible=True,
            test_cases=[
                "Test that input/output types match original",
                "Test with edge cases (empty input, single element)",
                "Verify numerical accuracy vs. original",
            ],
        )
    
    def generate_parallelization_fix(self, file_path: str, line_range: tuple,
                                     original_code: str, worker_count: int = 4) -> CodeFix:
        """Generate a parallelization improvement."""
        
        improved_code = f'''from concurrent.futures import ThreadPoolExecutor

# Parallel processing (replacing sequential loop)
with ThreadPoolExecutor(max_workers={worker_count}) as executor:
    results = list(executor.map(process_item, items))
'''
        
        return CodeFix(
            improvement_type=ImprovementType.PARALLELIZATION,
            file_path=file_path,
            line_range=line_range,
            original_code=original_code,
            improved_code=improved_code,
            explanation=f"Parallelized independent iterations using {worker_count} workers",
            risk_level=0.2,  # Slightly higher risk due to threading
            performance_gain=float(worker_count),  # Linear with worker count
            backwards_compatible=True,
            test_cases=[
                "Test that results are identical to sequential version",
                "Test with thread-safe operations only",
                "Verify no race conditions or deadlocks",
            ],
        )
    
    def generate_algorithm_fix(self, file_path: str, line_range: tuple,
                              original_code: str, old_complexity: str, 
                              new_complexity: str, new_code: str) -> CodeFix:
        """Generate an algorithmic improvement."""
        
        return CodeFix(
            improvement_type=ImprovementType.ALGORITHM,
            file_path=file_path,
            line_range=line_range,
            original_code=original_code,
            improved_code=new_code,
            explanation=f"Improved algorithm: {old_complexity} → {new_complexity}",
            risk_level=0.25,  # Higher risk for algorithm changes
            performance_gain=5.0,  # Typical for better algorithms
            backwards_compatible=True,
            test_cases=[
                "Test correctness with known inputs/outputs",
                "Test edge cases and boundary conditions",
                "Performance regression test (at least 2x speedup)",
                "Stress test with large inputs",
            ],
        )
    
    def generate_indexing_fix(self, file_path: str, line_range: tuple,
                             original_code: str, search_operation: str,
                             index_type: str = "dict") -> CodeFix:
        """Generate an indexing/lookup table improvement."""
        
        improved_code = f'''# Add index for faster lookups
{index_type}_index = {{key: value for key, value in ...}}

# Use index instead of linear search
{search_operation} -> {index_type}_index.get(key)
'''
        
        return CodeFix(
            improvement_type=ImprovementType.INDEXING,
            file_path=file_path,
            line_range=line_range,
            original_code=original_code,
            improved_code=improved_code,
            explanation=f"Added {index_type} index for O(1) lookups instead of O(n) search",
            risk_level=0.1,
            performance_gain=100.0,  # Huge potential gain (O(n) → O(1))
            backwards_compatible=True,
            test_cases=[
                f"Test that index is built correctly",
                f"Test that lookups return same results",
                f"Benchmark: should be >100x faster for large datasets",
            ],
        )
    
    def create_pull_request(self, changes: List[CodeFix], 
                           issue_description: str) -> PullRequest:
        """Create a complete pull request from code changes."""
        
        pr_id = f"self-pr-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        
        # Calculate aggregated metrics
        total_speedup = 1.0
        for change in changes:
            total_speedup *= change.performance_gain
        
        max_risk = max([c.risk_level for c in changes]) if changes else 0.0
        
        # Risk assessment
        if max_risk < 0.15:
            risk_assessment = "✅ SAFE - Low risk changes. All modifications are well-understood."
        elif max_risk < 0.25:
            risk_assessment = "⚠️ MEDIUM - Moderate risk. Changes require careful testing."
        else:
            risk_assessment = "🔴 HIGH - High risk changes. Requires extensive testing and validation."
        
        # Affected components
        affected = set()
        for change in changes:
            parts = change.file_path.split('/')
            if len(parts) > 1:
                affected.add(parts[1])  # e.g., 'memory', 'meta', 'lmm'
        
        title = f"Performance optimization: {changes[0].improvement_type.value}"
        if len(changes) > 1:
            title = f"Multi-optimization PR: {len(changes)} improvements"
        
        return PullRequest(
            pr_id=pr_id,
            title=title,
            description=f"Self-improvement PR addressing: {issue_description}",
            changes=changes,
            created_at=datetime.now(),
            risk_assessment=risk_assessment,
            expected_outcome=f"Overall performance improvement of {total_speedup:.1f}x expected",
            estimated_improvement=total_speedup,
            affected_components=sorted(list(affected)),
        )


def generate_improvements_from_analysis(analysis_report) -> List[PullRequest]:
    """Generate improvement PRs from code analysis results."""
    
    generator = ImprovementGenerator()
    pull_requests = []
    
    # Group issues by category and create PRs
    prs_created = {}
    
    for issue in analysis_report.top_priorities[:5]:
        category = issue.category.value
        
        if category == 'caching':
            fix = generator.generate_caching_fix(
                function_name="unknown",
                file_path=issue.file_path,
                line_range=(issue.line_number, issue.line_number + 5),
                original_code=issue.code_snippet,
            )
        
        elif category == 'vectorization':
            fix = generator.generate_vectorization_fix(
                file_path=issue.file_path,
                line_range=(issue.line_number, issue.line_number + 5),
                original_code=issue.code_snippet,
                operation="# Vectorized operation here",
            )
        
        elif category == 'parallel' or category == 'parallelization':
            fix = generator.generate_parallelization_fix(
                file_path=issue.file_path,
                line_range=(issue.line_number, issue.line_number + 5),
                original_code=issue.code_snippet,
                worker_count=4,
            )
        
        elif category == 'algorithm':
            fix = generator.generate_algorithm_fix(
                file_path=issue.file_path,
                line_range=(issue.line_number, issue.line_number + 5),
                original_code=issue.code_snippet,
                old_complexity="O(n²)",
                new_complexity="O(n log n)",
                new_code="# Improved algorithm here",
            )
        
        elif category == 'indexing':
            fix = generator.generate_indexing_fix(
                file_path=issue.file_path,
                line_range=(issue.line_number, issue.line_number + 5),
                original_code=issue.code_snippet,
                search_operation="linear_search",
            )
        
        else:
            continue
        
        # Create PR if not already created for this category
        if category not in prs_created:
            pr = generator.create_pull_request(
                changes=[fix],
                issue_description=issue.description
            )
            pull_requests.append(pr)
            prs_created[category] = pr
        else:
            # Add to existing PR
            prs_created[category].changes.append(fix)
    
    return pull_requests
