import os
from pathlib import Path
import json


class SkillGenerator:

    def __init__(self, base_path="jessica/generated_skills"):
        self.base_path = Path(base_path)
        self.base_path.mkdir(parents=True, exist_ok=True)

    def generate_skill(self, skill_name, description):

        skill_path = self.base_path / skill_name
        skill_path.mkdir(exist_ok=True)

        # generator code
        generator_file = skill_path / "generator.py"
        generator_file.write_text(self._generator_template(skill_name, description))

        # test file
        test_file = skill_path / "tests.py"
        test_file.write_text(self._test_template(skill_name))

        # config
        config_file = skill_path / "config.json"
        config_file.write_text(
            json.dumps(
                {
                    "name": skill_name,
                    "description": description,
                    "version": "0.1",
                    "author": "Jessica AI"
                },
                indent=2
            )
        )

        # documentation
        readme_file = skill_path / "README.md"
        readme_file.write_text(self._readme_template(skill_name, description))

        return skill_path

    def _generator_template(self, skill_name, description):

        return f'''
"""
Skill: {skill_name}
Description: {description}
Generated by Jessica AI
"""

class {skill_name.capitalize()}Skill:

    def execute(self, input_data):
        print("Executing skill: {skill_name}")
        return "Skill executed successfully"
'''

    def _test_template(self, skill_name):

        return f'''
def test_{skill_name}():

    from generator import {skill_name.capitalize()}Skill

    skill = {skill_name.capitalize()}Skill()
    result = skill.execute("test")

    assert result is not None
'''

    def _readme_template(self, skill_name, description):

        return f'''
# {skill_name}

Generated by Jessica AI.

## Description

{description}

## Usage

Import the skill and call execute().
'''
