"""Phase 7.1: Action Proposal Structures - Immutable frozen dataclasses.

All proposal structures are frozen (immutable) to prevent accidental modifications.
Phase 7.1 is purely advisory - generates proposals but does NOT execute.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Optional
from uuid import uuid4

from jessica.execution.decision_structures import RiskLevel


class ProposalStatus(Enum):
    """Status lifecycle for action proposals."""
    PROPOSED = "proposed"          # Initial state: proposal generated
    APPROVED = "approved"          # Human approved the proposal
    REJECTED = "rejected"          # Human rejected the proposal
    EXECUTED = "executed"          # Action has been executed (Phase 5.5)
    FAILED = "failed"              # Execution failed (from Phase 5.3 reflection)
    CANCELLED = "cancelled"        # Proposal was cancelled


@dataclass(frozen=True)
class ActionProposal:
    """Immutable proposal for a human-approved action.
    
    Generated by Phase 7.1 based on:
    - Approved intent (Phase 5.1.5)
    - Decision context (Phase 6)
    
    This proposal is purely advisory - it does NOT trigger execution.
    Execution requires explicit human approval + Phase 5.5 call.
    
    All fields are immutable (@dataclass(frozen=True)).
    """
    
    proposal_id: str                    # Unique proposal identifier
    intent_id: str                      # Reference to Phase 5.1.5 approved intent
    intent_summary: str                 # Human-readable intent summary
    proposed_action: str                # Human-readable action description
    required_permissions: List[str]     # Permissions needed (e.g., ["file_read", "network"])
    risk_level: RiskLevel               # Risk assessment (VERY_LOW to VERY_HIGH)
    rationale: str                      # Why this action is proposed
    reversible: bool                    # Can this action be undone?
    created_at: datetime                # When proposal was generated
    status: ProposalStatus = ProposalStatus.PROPOSED  # Current status
    approval_timestamp: Optional[datetime] = None    # When human approved (if approved)
    approval_reason: Optional[str] = None             # Why human approved/rejected
    notes: List[str] = field(default_factory=list)   # Additional notes
    
    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        return {
            "proposal_id": self.proposal_id,
            "intent_id": self.intent_id,
            "intent_summary": self.intent_summary,
            "proposed_action": self.proposed_action,
            "required_permissions": self.required_permissions,
            "risk_level": self.risk_level.value,
            "rationale": self.rationale,
            "reversible": self.reversible,
            "created_at": self.created_at.isoformat(),
            "status": self.status.value,
            "approval_timestamp": self.approval_timestamp.isoformat() if self.approval_timestamp else None,
            "approval_reason": self.approval_reason,
            "notes": self.notes,
        }


def create_action_proposal(
    intent_id: str,
    intent_summary: str,
    proposed_action: str,
    required_permissions: List[str],
    risk_level: RiskLevel,
    rationale: str,
    reversible: bool,
    proposal_id: Optional[str] = None,
    notes: Optional[List[str]] = None,
) -> ActionProposal:
    """Factory function to create ActionProposal.
    
    Args:
        intent_id: Reference to Phase 5.1.5 approved intent
        intent_summary: Human-readable intent summary
        proposed_action: Human-readable action description
        required_permissions: List of required permissions
        risk_level: Risk assessment
        rationale: Why this action is proposed
        reversible: Can it be undone?
        proposal_id: Optional custom ID (default: auto-generated)
        notes: Optional additional notes
    
    Returns:
        Immutable ActionProposal instance
    """
    return ActionProposal(
        proposal_id=proposal_id or f"prop_{uuid4().hex[:12]}",
        intent_id=intent_id,
        intent_summary=intent_summary,
        proposed_action=proposed_action,
        required_permissions=required_permissions,
        risk_level=risk_level,
        rationale=rationale,
        reversible=reversible,
        created_at=datetime.now(),
        notes=notes or [],
    )
